//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbiHue.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmbiHue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bridgePointPaint {
            get {
                object obj = ResourceManager.GetObject("bridgePointPaint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the button on the bridge. Once you have done this click on the pair button below..
        /// </summary>
        internal static string FormConfiguration_FormConfiguration_Load_Press_the_button_on_the_bridge__Once_you_have_done_this_click_on_the_pair_button_below_ {
            get {
                return ResourceManager.GetString("FormConfiguration_FormConfiguration_Load_Press_the_button_on_the_bridge__Once_you" +
                        "_have_done_this_click_on_the_pair_button_below_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration failed to be loaded. Halting application. Goodbye ....
        /// </summary>
        internal static string FormMain_CheckForConfiguration_Configuration_failed_to_be_loaded__Halting_application__Goodbye____ {
            get {
                return ResourceManager.GetString("FormMain_CheckForConfiguration_Configuration_failed_to_be_loaded__Halting_applica" +
                        "tion__Goodbye____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration has been detected. Please run the initial setup to start..
        /// </summary>
        internal static string FormMain_CheckForConfiguration_No_configuration_has_been_detected__Please_run_the_initial_setup_to_start_ {
            get {
                return ResourceManager.GetString("FormMain_CheckForConfiguration_No_configuration_has_been_detected__Please_run_the" +
                        "_initial_setup_to_start_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not paired yet!.
        /// </summary>
        internal static string FormMain_CheckForConfiguration_Not_paired_yet_ {
            get {
                return ResourceManager.GetString("FormMain_CheckForConfiguration_Not_paired_yet_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Bridge has not been paired yet. Do you wish to do this now? Note: Without pairing this program cannot do anything..
        /// </summary>
        internal static string FormMain_CheckForConfiguration_The_Bridge_has_not_been_paired_yet__Do_you_wish_to_do_this_now__Note__Without_pairing_this_program_cannot_do_anything_ {
            get {
                return ResourceManager.GetString("FormMain_CheckForConfiguration_The_Bridge_has_not_been_paired_yet__Do_you_wish_to" +
                        "_do_this_now__Note__Without_pairing_this_program_cannot_do_anything_", resourceCulture);
            }
        }
    }
}
